using LocalScribe.Core.Projection;
using Xunit;

namespace LocalScribe.Core.Tests;

/// <summary>Pins the two Round 1 strings across their move off DocxRenderer (design 2026-08-04
/// section 2). A move must not reword an evidentiary notice, and only an explicit assertion
/// makes that impossible to do by accident.</summary>
public sealed class ExportNoticesTests
{
    [Fact]
    public void Disclaimer_is_byte_identical_to_the_round_1_string()
        => Assert.Equal(
            "This transcript was generated by automated speech recognition and may contain errors. "
            + "It is not a certified record.",
            ExportNotices.Disclaimer);

    [Fact]
    public void In_progress_notice_is_byte_identical_to_the_round_1_string()
        => Assert.Equal(
            "IN-PROGRESS RECORDING \u2014 transcript incomplete, speaker separation not yet applied.",
            ExportNotices.InProgressNotice);

    [Fact]
    public void Excerpt_notice_is_the_locked_wording()
        => Assert.Equal("EXCERPT \u2014 not the complete transcript.", ExportNotices.ExcerptNotice);

    [Fact]
    public void Summary_heading_does_not_collide_with_the_content_own_first_header()
    {
        // AssistantPrompts.SectionHeaders[0] is literally "Summary"; the export section must not
        // repeat it (design 2026-08-04 section 7).
        Assert.Equal("Assistant summary", ExportNotices.SummaryHeading);
        Assert.NotEqual("Summary", ExportNotices.SummaryHeading);
    }

    [Fact]
    public void Summary_scope_notice_is_the_locked_wording()
        => Assert.Equal("Summarises the complete transcript, not this excerpt.",
            ExportNotices.SummaryCoversMoreThanExcerpt);
}
