using System.Globalization;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;
namespace LocalScribe.Core.Projection;

/// <summary>The user-facing export toggles (design 3.3 + 2026-08-02 item 5). House style mirrors
/// PhantomBleedOptions: sealed record + { get; init; } with inline defaults. Format-neutral and
/// shared deliberately by the .docx and .md export renderers.</summary>
public sealed record DocxOptions
{
    public bool IncludeTimestamps { get; init; } = true;
    public bool IncludeMarkers { get; init; } = true;
    /// <summary>Extra mid-turn stamp cadence (design 2026-08-02 item 5): a stamp-only continuation
    /// paragraph starts at the first segment boundary at/after this many ms since the last shown
    /// stamp. 0 (default) = off. Renderers force it off when IncludeTimestamps is false.</summary>
    public int TimestampIntervalMs { get; init; } = 0;
}

/// <summary>Page size for an exported .docx. Chosen from the machine locale AT the export call site
/// (RegionInfo) and passed in - the ONLY machine-locale dependence, scoped to page size (spec 11.2).</summary>
public enum DocxPageSize { A4, Letter }

/// <summary>Serializes a .docx transcript projection (spec 11.2, design 2026-08-02 item 6) into a
/// stream, in the courtroom layout: each turn is one paragraph in the named TranscriptTurn style -
/// bold "[00:00] Name:" label, tab, text - with a hanging indent so wrapped lines align at a text
/// column auto-sized from the longest label. Same render model as MarkdownRenderer (TranscriptHeader
/// + rows) plus the SessionTextView metadata block (user-curated participants, NEVER speakers.json
/// clusters) and a NON-OPTIONAL machine-generated-accuracy disclaimer. All TEXT is invariant-culture;
/// markers render italic in the text column. Rows arrive pre-resolved from TranscriptProjection.Build
/// - this never re-runs vocabulary/edits/dedup/NameResolver.</summary>
public static class DocxRenderer
{
    // Word page dimensions are in twips (1/1440 inch). A4 = 210x297mm; Letter = 8.5x11in.
    private const int A4WidthTwips = 11906, A4HeightTwips = 16838;
    private const int LetterWidthTwips = 12240, LetterHeightTwips = 15840;
    // Courtroom page geometry (design 2026-08-02 item 6): 1" margins, 0.5" header/footer.
    private const int MarginTwips = 1440, HeaderFooterTwips = 720;
    // Text column sizing: estimated bold-11pt character advance plus label padding, clamped to
    // [1.5", 3.0"] so short labels still get a real gutter and marathon names cannot eat the page
    // (overlong labels overrun one line gracefully; the hanging indent keeps wrapped lines aligned).
    private const int TwipsPerLabelChar = 120, LabelPadTwips = 240;
    private const int MinTextColTwips = 2160, MaxTextColTwips = 4320;

    public const string Disclaimer =
        "This transcript was generated by automated speech recognition and may contain errors. "
        + "It is not a certified record.";

    public static DocxPageSize PageSizeForRegion(RegionInfo region)
        => region.TwoLetterISORegionName is "US" or "CA" ? DocxPageSize.Letter : DocxPageSize.A4;

    public static void Write(Stream output, TranscriptHeader header, SessionTextView meta,
        ExportProvenance provenance, IReadOnlyList<DisplayRow> rows, string timestampsMode,
        DocxPageSize pageSize, DocxOptions options)
    {
        using var doc = WordprocessingDocument.Create(output, WordprocessingDocumentType.Document);
        var mainPart = doc.AddMainDocumentPart();
        mainPart.Document = new Document();
        var body = mainPart.Document.AppendChild(new Body());

        int textCol = TextColumnTwips(rows, options, timestampsMode, header.StartedAtLocal);
        AddStyles(mainPart, textCol);

        // Metadata header block.
        body.AppendChild(Heading(meta.Title));
        body.AppendChild(MetaLine("App", header.App));
        body.AppendChild(MetaLine("Date",
            header.StartedAtLocal.ToString("yyyy-MM-dd HH:mm", CultureInfo.InvariantCulture)));
        body.AppendChild(MetaLine("Matter(s)",
            meta.Matters.Count == 0 ? "(none)" : string.Join(", ", meta.Matters)));
        body.AppendChild(MetaLine("Participants",
            meta.Participants.Count == 0 ? "(none)" : string.Join(", ", meta.Participants)));
        body.AppendChild(MetaLine("Medium", meta.Medium));
        if (!string.IsNullOrEmpty(meta.Description)) body.AppendChild(MetaLine("Description", meta.Description));
        body.AppendChild(DisclaimerLine());
        // Spacer before the turns - suppressed like the rest of the header so line 1 is content.
        body.AppendChild(new Paragraph(new ParagraphProperties(new SuppressLineNumbers())));

        foreach (var row in rows)
        {
            if (row.IsMarker)
            {
                if (options.IncludeMarkers) body.AppendChild(MarkerLine(row.Text, textCol));
                continue;
            }
            // Cadence chunking (design 2026-08-02 item 5): chunk 0 is the normal turn; later
            // chunks are stamp-only continuation paragraphs in the same geometry (no name).
            // Interval 0 (or timestamps off) yields one whole-row chunk - output unchanged.
            var chunks = TimestampCadence.Chunk(row,
                options.IncludeTimestamps ? options.TimestampIntervalMs : 0);
            body.AppendChild(TurnParagraph(
                TurnLabel(row, options, timestampsMode, header.StartedAtLocal), chunks[0].Text));
            for (int i = 1; i < chunks.Count; i++)
                body.AppendChild(TurnParagraph(
                    new TurnLabelParts(
                        "[" + TimestampFormat.Stamp(chunks[i].StampMs, timestampsMode, header.StartedAtLocal) + "]",
                        "", ""),
                    chunks[i].Text));
        }

        // Per-page footer + locale page size in section properties (sectPr MUST be the last child
        // of body). design 2026-08-03 section 2: {transcript name} at the left margin, "Page N of
        // M" at a right tab on the usable width. The cached "1"/"1" results are the placeholders
        // Word replaces when it paginates. Field instruction text is invariant by construction.
        (int w, int h) = pageSize == DocxPageSize.Letter
            ? (LetterWidthTwips, LetterHeightTwips) : (A4WidthTwips, A4HeightTwips);
        int usableWidth = w - 2 * MarginTwips;
        var footerPart = mainPart.AddNewPart<FooterPart>();
        footerPart.Footer = new Footer(new Paragraph(
            new ParagraphProperties(
                new Tabs(new TabStop { Val = TabStopValues.Right, Position = usableWidth })),
            new Run(MakeText(meta.Title)),
            new Run(new TabChar()),
            new Run(MakeText("Page ")),
            new Run(new FieldChar { FieldCharType = FieldCharValues.Begin }),
            new Run(new FieldCode(" PAGE ") { Space = SpaceProcessingModeValues.Preserve }),
            new Run(new FieldChar { FieldCharType = FieldCharValues.Separate }),
            new Run(MakeText("1")),
            new Run(new FieldChar { FieldCharType = FieldCharValues.End }),
            new Run(MakeText(" of ")),
            new Run(new FieldChar { FieldCharType = FieldCharValues.Begin }),
            new Run(new FieldCode(" NUMPAGES ") { Space = SpaceProcessingModeValues.Preserve }),
            new Run(new FieldChar { FieldCharType = FieldCharValues.Separate }),
            new Run(MakeText("1")),
            new Run(new FieldChar { FieldCharType = FieldCharValues.End })));
        string footerId = mainPart.GetIdOfPart(footerPart);

        // Running head (design 2026-08-03 section 3): matter + date at the left margin, the
        // current speaker at a right tab. The speaker is a STYLEREF field, not text we compose -
        // only Word knows where its own page breaks fall. The left half IS composed here, because
        // STYLEREF cannot truncate and a long matter would otherwise collide with the speaker.
        var headerPart = mainPart.AddNewPart<HeaderPart>();
        headerPart.Header = new Header(new Paragraph(
            new ParagraphProperties(
                new Tabs(new TabStop { Val = TabStopValues.Right, Position = usableWidth }),
                new ParagraphBorders(new BottomBorder
                { Val = BorderValues.Single, Size = 4U, Space = 4U, Color = "auto" })),
            new Run(MakeText(HeaderLeft(header, meta))),
            new Run(new TabChar()),
            new Run(new FieldChar { FieldCharType = FieldCharValues.Begin }),
            new Run(new FieldCode(" STYLEREF \"TranscriptSpeaker\" ")
            { Space = SpaceProcessingModeValues.Preserve }),
            new Run(new FieldChar { FieldCharType = FieldCharValues.Separate }),
            // Caps here too: STYLEREF returns the stored name, and the body shows it in caps via
            // the character style, so the head must match.
            new Run(new RunProperties(new Caps()), MakeText("")),
            new Run(new FieldChar { FieldCharType = FieldCharValues.End })));
        string headerId = mainPart.GetIdOfPart(headerPart);

        // Page 1 carries the metadata block, which names everything the running head would - so
        // the head is suppressed there via TitlePg + an EMPTY first-page header.
        var firstHeaderPart = mainPart.AddNewPart<HeaderPart>();
        firstHeaderPart.Header = new Header(new Paragraph());
        string firstHeaderId = mainPart.GetIdOfPart(firstHeaderPart);

        body.AppendChild(new SectionProperties(
            new HeaderReference { Type = HeaderFooterValues.Default, Id = headerId },
            new HeaderReference { Type = HeaderFooterValues.First, Id = firstHeaderId },
            new FooterReference { Type = HeaderFooterValues.Default, Id = footerId },
            // Same part id as Default: TitlePg suppresses the page-1 footer unless a First
            // reference exists, and page 1 must still show "Page 1 of N".
            new FooterReference { Type = HeaderFooterValues.First, Id = footerId },
            new PageSize { Width = (UInt32Value)(uint)w, Height = (UInt32Value)(uint)h },
            // Explicit margins make the tab geometry predictable (sectPr schema order: pgSz, pgMar).
            new PageMargin
            {
                Top = MarginTwips, Right = (uint)MarginTwips,
                Bottom = MarginTwips, Left = (uint)MarginTwips,
                Header = (uint)HeaderFooterTwips, Footer = (uint)HeaderFooterTwips, Gutter = 0U,
            },
            // Courtroom line numbers (design 2026-08-02 item 6): every 5th line, restart per page,
            // counting transcript content only (header paragraphs carry SuppressLineNumbers).
            new LineNumberType { CountBy = 5, Restart = LineNumberRestartValues.NewPage },
            new TitlePage()));
    }

    /// <summary>The composed left half of the running head: first matter (or the title when the
    /// session is untagged) and the start date. Composed rather than STYLEREF'd because a long
    /// matter must be truncatable - STYLEREF cannot truncate (design 2026-08-03 section 3).</summary>
    private static string HeaderLeft(TranscriptHeader header, SessionTextView meta)
    {
        const int MaxChars = 60;
        string left = meta.Matters.Count > 0 ? meta.Matters[0] : meta.Title;
        if (left.Length > MaxChars) left = left[..(MaxChars - 1)] + "\u2026";
        return left + " \u00B7 "
            + header.StartedAtLocal.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);
    }

    /// <summary>O(n) pre-pass (design 2026-08-02 item 6): size the text column off the longest turn
    /// label. Continuation stamps ("[1:02:03]") are always narrower than the 1.5" floor, so only
    /// full labels need measuring.</summary>
    private static int TextColumnTwips(IReadOnlyList<DisplayRow> rows, DocxOptions options,
        string timestampsMode, DateTimeOffset startedAtLocal)
    {
        int longest = 0;
        foreach (var row in rows)
            if (!row.IsMarker)
                longest = Math.Max(longest,
                    TurnLabel(row, options, timestampsMode, startedAtLocal).Length);
        return Math.Clamp(longest * TwipsPerLabelChar + LabelPadTwips, MinTextColTwips, MaxTextColTwips);
    }

    /// <summary>The three pieces of a turn label, kept separate because only the NAME may carry
    /// the TranscriptSpeaker character style - STYLEREF in the page header returns that run's text
    /// verbatim (design 2026-08-03 section 3). Length is what TextColumnTwips measures.</summary>
    private readonly record struct TurnLabelParts(string Stamp, string Name, string Suffix)
    {
        public int Length => Stamp.Length + Name.Length + Suffix.Length;
    }

    private static TurnLabelParts TurnLabel(DisplayRow row, DocxOptions options, string timestampsMode,
        DateTimeOffset startedAtLocal)
        => new(
            options.IncludeTimestamps
                ? "[" + TimestampFormat.Stamp(row.StartMs, timestampsMode, startedAtLocal) + "] "
                : "",
            row.DisplayName ?? "",
            ":");

    /// <summary>Bold stamp -> styled name -> bold suffix -> tab -> text. The TranscriptTurn style
    /// carries the hanging indent and tab stop, so a recipient can retune the whole document by
    /// editing one style in Word.</summary>
    private static Paragraph TurnParagraph(TurnLabelParts label, string text)
    {
        var p = new Paragraph(new ParagraphProperties(new ParagraphStyleId { Val = "TranscriptTurn" }));
        if (label.Stamp.Length > 0)
            p.AppendChild(new Run(new RunProperties(new Bold()), MakeText(label.Stamp)));
        if (label.Name.Length > 0)
            p.AppendChild(new Run(
                new RunProperties(new RunStyle { Val = "TranscriptSpeaker" }), MakeText(label.Name)));
        if (label.Suffix.Length > 0)
            p.AppendChild(new Run(new RunProperties(new Bold()), MakeText(label.Suffix)));
        p.AppendChild(new Run(new TabChar()));
        p.AppendChild(new Run(MakeText(text)));
        return p;
    }

    private static Paragraph MarkerLine(string text, int textCol)
        => new(new ParagraphProperties(
                new Indentation { Left = textCol.ToString(CultureInfo.InvariantCulture) }),
            new Run(new RunProperties(new Italic()), MakeText("[" + text + "]")));

    private static void AddStyles(MainDocumentPart mainPart, int textCol)
    {
        string col = textCol.ToString(CultureInfo.InvariantCulture);
        var stylesPart = mainPart.AddNewPart<StyleDefinitionsPart>();
        stylesPart.Styles = new Styles(
            // Arial pinned at the document default (design 2026-08-03 section 4), NOT on the turn
            // style: with no rFonts and no theme part Word fell back to Times New Roman, and that
            // fallback reached headings, footer, header and line numbers too. Size stays at 11pt -
            // TextColumnTwips' character-advance arithmetic depends on it.
            new DocDefaults(new RunPropertiesDefault(new RunPropertiesBaseStyle(
                new RunFonts { Ascii = "Arial", HighAnsi = "Arial", ComplexScript = "Arial" },
                new FontSize { Val = "22" }, new FontSizeComplexScript { Val = "22" }))),
            new Style(
                new StyleName { Val = "Transcript Turn" },
                new StyleParagraphProperties(
                    new Tabs(new TabStop { Val = TabStopValues.Left, Position = textCol }),
                    new Indentation { Left = col, Hanging = col },
                    // 6pt (120 twentieths of a point) after each turn.
                    new SpacingBetweenLines { After = "120" },
                    new WidowControl()))
            { Type = StyleValues.Paragraph, StyleId = "TranscriptTurn" }
            ,
            // Pure CHARACTER style (design 2026-08-03 sections 3-4). Two hard requirements:
            // (1) type=character, never linked - Word's STYLEREF cannot see a linked style applied
            //     to part of a paragraph, and this is applied to a run inside the turn paragraph;
            // (2) Caps as a FORMAT, never an uppercased string - STYLEREF returns the underlying
            //     text, so uppercasing the data would destroy the real name in the document body
            //     to achieve a display effect.
            new Style(
                new StyleName { Val = "Transcript Speaker" },
                new StyleRunProperties(new Bold(), new Caps()))
            { Type = StyleValues.Character, StyleId = "TranscriptSpeaker" });
    }

    private static Text MakeText(string s) => new(s) { Space = SpaceProcessingModeValues.Preserve };
    private static Paragraph Heading(string title)
        => new(new ParagraphProperties(new SuppressLineNumbers()),
            new Run(new RunProperties(new Bold(), new FontSize { Val = "32" }), MakeText(title)));
    private static Paragraph MetaLine(string label, string value)
        => new(new ParagraphProperties(new SuppressLineNumbers()),
            new Run(new RunProperties(new Bold()), MakeText(label + ": ")), new Run(MakeText(value)));
    /// <summary>Italic disclaimer closed by a thin 0.5pt rule (design 2026-08-02 item 6) that
    /// separates the unnumbered metadata block from the numbered transcript body.</summary>
    private static Paragraph DisclaimerLine()
        => new(new ParagraphProperties(
                new SuppressLineNumbers(),
                new ParagraphBorders(new BottomBorder
                { Val = BorderValues.Single, Size = 4U, Space = 4U, Color = "auto" })),
            new Run(new RunProperties(new Italic()), MakeText(Disclaimer)));
}
