using System.Globalization;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;
namespace LocalScribe.Core.Projection;

/// <summary>The two user-facing docx toggles (design 3.3). House style mirrors PhantomBleedOptions:
/// sealed record + { get; init; } with inline defaults.</summary>
public sealed record DocxOptions
{
    public bool IncludeTimestamps { get; init; } = true;
    public bool IncludeMarkers { get; init; } = true;
}

/// <summary>Page size for an exported .docx. Chosen from the machine locale AT the export call site
/// (RegionInfo) and passed in - the ONLY machine-locale dependence, scoped to page size (spec 11.2).</summary>
public enum DocxPageSize { A4, Letter }

/// <summary>Serializes a .docx transcript projection (spec 11.2, design 3.3) into a stream. Same render
/// model as MarkdownRenderer/PlainTextRenderer (TranscriptHeader + rows) plus the SessionTextView
/// metadata block (user-curated participants, NEVER speakers.json clusters), a NON-OPTIONAL
/// machine-generated-accuracy disclaimer, a per-page footer, and a locale page size. All TEXT is
/// invariant-culture; markers render italic, turn labels bold. Rows arrive pre-resolved from
/// TranscriptProjection.Build - this never re-runs vocabulary/edits/dedup/NameResolver.</summary>
public static class DocxRenderer
{
    // Word page dimensions are in twips (1/1440 inch). A4 = 210x297mm; Letter = 8.5x11in.
    private const int A4WidthTwips = 11906, A4HeightTwips = 16838;
    private const int LetterWidthTwips = 12240, LetterHeightTwips = 15840;

    public const string Disclaimer =
        "This transcript was generated by automated speech recognition and may contain errors. "
        + "It is not a certified record.";

    public static DocxPageSize PageSizeForRegion(RegionInfo region)
        => region.TwoLetterISORegionName is "US" or "CA" ? DocxPageSize.Letter : DocxPageSize.A4;

    public static void Write(Stream output, TranscriptHeader header, SessionTextView meta,
        IReadOnlyList<DisplayRow> rows, string timestampsMode, string footerText,
        DocxPageSize pageSize, DocxOptions options)
    {
        using var doc = WordprocessingDocument.Create(output, WordprocessingDocumentType.Document);
        var mainPart = doc.AddMainDocumentPart();
        mainPart.Document = new Document();
        var body = mainPart.Document.AppendChild(new Body());

        // Metadata header block.
        body.AppendChild(Heading(meta.Title));
        body.AppendChild(MetaLine("App", header.App));
        body.AppendChild(MetaLine("Date",
            header.StartedAtLocal.ToString("yyyy-MM-dd HH:mm", CultureInfo.InvariantCulture)));
        body.AppendChild(MetaLine("Matter(s)",
            meta.Matters.Count == 0 ? "(none)" : string.Join(", ", meta.Matters)));
        body.AppendChild(MetaLine("Participants",
            meta.Participants.Count == 0 ? "(none)" : string.Join(", ", meta.Participants)));
        body.AppendChild(MetaLine("Medium", meta.Medium));
        if (!string.IsNullOrEmpty(meta.Description)) body.AppendChild(MetaLine("Description", meta.Description));
        body.AppendChild(ItalicLine(Disclaimer));
        body.AppendChild(new Paragraph());   // spacer before the turns

        foreach (var row in rows)
        {
            if (row.IsMarker)
            {
                if (options.IncludeMarkers) body.AppendChild(ItalicLine("[" + row.Text + "]"));
                continue;
            }
            string label = options.IncludeTimestamps
                ? "[" + TimestampFormat.Stamp(row.StartMs, timestampsMode, header.StartedAtLocal)
                    + "] " + row.DisplayName + ": "
                : row.DisplayName + ": ";
            body.AppendChild(new Paragraph(
                new Run(new RunProperties(new Bold()), MakeText(label)),
                new Run(MakeText(row.Text))));
        }

        // Per-page footer + locale page size in section properties (MUST be the last child of body).
        var footerPart = mainPart.AddNewPart<FooterPart>();
        footerPart.Footer = new Footer(new Paragraph(new Run(MakeText(footerText))));
        string footerId = mainPart.GetIdOfPart(footerPart);
        (int w, int h) = pageSize == DocxPageSize.Letter
            ? (LetterWidthTwips, LetterHeightTwips) : (A4WidthTwips, A4HeightTwips);
        body.AppendChild(new SectionProperties(
            new FooterReference { Type = HeaderFooterValues.Default, Id = footerId },
            new PageSize { Width = (UInt32Value)(uint)w, Height = (UInt32Value)(uint)h }));
    }

    private static Text MakeText(string s) => new(s) { Space = SpaceProcessingModeValues.Preserve };
    private static Paragraph Heading(string title)
        => new(new Run(new RunProperties(new Bold(), new FontSize { Val = "32" }), MakeText(title)));
    private static Paragraph MetaLine(string label, string value)
        => new(new Run(new RunProperties(new Bold()), MakeText(label + ": ")), new Run(MakeText(value)));
    private static Paragraph ItalicLine(string s)
        => new(new Run(new RunProperties(new Italic()), MakeText(s)));
}
