namespace LocalScribe.Core.Projection;

/// <summary>Fixed strings shared by every export renderer (design 2026-08-04 section 2). Moved
/// off DocxRenderer, which MarkdownRenderer already reached into for text and which a third and
/// fourth renderer would too. Non-ASCII via \u escapes (ASCII source rule) - a literal em dash
/// here breaks the byte-scan gate.</summary>
public static class ExportNotices
{
    /// <summary>Non-optional on every exported transcript (design 3.3).</summary>
    public const string Disclaimer =
        "This transcript was generated by automated speech recognition and may contain errors. "
        + "It is not a certified record.";

    /// <summary>Stamped on a session exported mid-recording (design 2026-08-03 section 11).</summary>
    public const string InProgressNotice =
        "IN-PROGRESS RECORDING \u2014 transcript incomplete, speaker separation not yet applied.";

    /// <summary>Mandatory on every page of a time-range excerpt (design 2026-08-04 section 8),
    /// per the locked no-content-deletion rule.</summary>
    public const string ExcerptNotice = "EXCERPT \u2014 not the complete transcript.";

    /// <summary>Deliberately NOT "Summary": the generated content's own first section header is
    /// literally "## Summary" (AssistantPrompts.SectionHeaders), and the two would collide.</summary>
    public const string SummaryHeading = "Assistant summary";

    /// <summary>Stamped in the summary block when the transcript is EXCERPTED but the summary
    /// itself was generated over the complete transcript (whole-branch review fix 2):
    /// IncludeSummary and ExcerptRange are orthogonal options, so a user can tick both, and a
    /// reader must not be left guessing whether the summary describes the excerpt or the whole
    /// session. Independent of the stale-summary notice above - a CURRENT summary in an excerpt
    /// still needs this, and a stale summary in an excerpt gets both.</summary>
    public const string SummaryCoversMoreThanExcerpt =
        "Summarises the complete transcript, not this excerpt.";

    /// <summary>Appended to the turn label of a row whose text a human corrected (Tier 1 T1-8).
    /// Leading space included so callers concatenate without composing the spacing three times.
    /// Says "text corrected", not "edited": speaker reassignments and splits are also human edits
    /// and are counted on the Human edits metadata line - this mark is only about the WORDS.</summary>
    public const string CorrectedTurnMark = " [text corrected]";
}
